### ISSUE TITLE
Issue with parallelisation in msiterunLWFB90

### ISSUE THREAD

**Issue by rhabel** [pschmidtwalter/LWFBrook90R#50]
Hello, 
I have the following question/request:

When running a large number of points parallelly with msiterunLWFB90, it sometimes happens that the soil parameters of certain points are set in a way that makes the individual LWFB90 process run for ages, in which case, the core is blocked. If this happens let's say 4 times on a 4-core cpu, the whole process basically stops. 
In my case, the soil data is generated automatically for thousands of points so it is very hard to check, which points cause the issue, and that makes it tricky to change the soil data these points beforehand or to exclude them. The process bar just stops at some point without telling which points are blocking the cores.

Is it possible to include a maximum simulation duration (i.e. sim.max = 1000s), so that if that if sim.max is exceeded, the respective list element in "res" just becomes an error/warning message or NULL-dataframes, but the process continues?
This would immensely help to run a number of points that is too large to check the soil data of each point manually.

**Comment by trotsiuk** [comment]
Similar to the previous issue #18

**Comment by pschmidtwalter** [comment]
I wouldn't say this is similar to #18. This current issue accepts the mentioned issue, and asks for a work around...
For the old windows commandline tool b90.exe I used an external script to monitor execution times and killed b90.exe instances that ran too long. However, this is not possible here because b90 runs in (parallel) Rsessions, and there is no externally visible information which of the single runs is actually stuck.

A brief web-search gave some hints:

-  `setTimeLimit` (base-R) can timeout a "top-level computation, that is a command line (including any continuation lines) entered at the console or from a file. For compiled code, time limits can only be checked at certain points, that need to be specified by the code author"
-  Such points can be set in Fortran using the subroutine rchkusr() (https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Allowing-interrupts)

I will try this out and report.

**Comment by trotsiuk** [comment]
I would still argue that this is the same issue. The core is blocked due to endless iteration of the `FWETK` function. It simply can't find the suitable parameter end run forever. I'm sure if we look more into the @rhabel issue, it will boil down to the `FWETK` function. I had the similar story. I was running the simulation on cluster with 20 corres and then one by one corres were blocked. So basically after ca. 30000 sites all cores were blocked. I had to find each individual site which block the core and search for the issue. The issue boiled down to the `FWETK` function #18. The solution can be either way: 

- set the maximum iteration (recommended as independent of the time single simulation is running)
- maximim simulation duration (number of tries (iterations) will depend on the single run duration).

**Comment by rhabel** [comment]
I think you are right in that the issue with certain runs blocking cores could either be solved by setting a maximum amount of iterations (currently implemented by ItMax = 50, if I read your commit in #18 correctly) or a maximum simulation duration. 

However, as the package currently works, a final user who wants to run thousands of sites just sees the "working" cores disappear one by one (and with "working" here I mean calculating multiple sites one by one). If I was able to set the maximal number of Iterations as a solution, firstly, I wouldn't know which site actually needed this, and which ones are fine with the current ItMax. Plus, given that the time for one iteration is unknown and flexible, I wouldn't know to what value I'd have to change ItMax to actually make a difference.

On the contrary, if the workaround based on a maximum simulation time was implemented, one could say: With X sites to calculate and with a maximum duration time of Y, I can start the simulation time and have a result I can work with in Z h. Plus, this way I would directly know from the results-list, which sites caused the issue, if let's say LWFBrook90R returned a "timeout"-message for these points. I think this second option would be more handy.

**Comment by trotsiuk** [comment]
I believe both option application depends on the end requirements and priorities.
In the original `Brook90` there was a maximum number of iteration to find the convergence, in the later `LWF-Brook90` this part was commented out (dis-activated).

**Comment by pschmidtwalter** [comment]
I implemented a timeout-argument, it is checked each time when iteration starts. It works so far for normal cases. However this might not be enough, because if iterations get stuck, it will somehow detect this only when the iteration finishes. I do not have a good test file as an example. Can somebody provide me with an example running endlessly (e.g. bad soil parameters?).

**Comment by pschmidtwalter** [comment]
I now also reimplemented the maximum iterations. So, now we would really need an example parameter set that potentially runs forever to perform some tests... Would it be possible to look one up in your archives @trotsiuk ?
Thanks!

**Comment by pschmidtwalter** [comment]
Hi @rhabel!
I'd recommend for now to make use of the new timelimit-argument for large multisite-simulations. You could simulate each site only for a couple of days (the error you describe appears before the simulation day loop really started), and set the timelimit to 100 seconds, so that after your multirun finished, errors should be returned in every case where a site simulation ran longer. Then we can identify some bad parameter sets to reproduce the error. Could you then send a parameter file, so we have a test case to work on? 
All the best
Paul
