### ISSUE TITLE
Species settings (Picea abies)

### ISSUE THREAD

**Issue by marekie** [pschmidtwalter/LWFBrook90R#64]
For function `vegperiod` the argument `species` comprises three different settings for _Picea abies_ ("Picea abies (frueh)", "Picea abies (spaet)", "Picea abies (noerdl.)"). What do these specifications refer to and how to decide which one to use?

**Comment by pschmidtwalter** [comment]
Sorry for the late reply.
I always use 'Picea abies (frueh)', because this was the basic setting for spruce in the Acces-UI for the LWF-Brook90 model.
For more information on these settings maybe ask @rnuske, the package maintainer of the [vegperiod-package](https://github.com/rnuske/vegperiod). 

However I fear that we would have to look at the thesis of A. Menzel to get more information: 
@book{menzel_phanologie_1997,
	series = {Forstliche {Forschungsberichte} {München}},
	title = {Phänologie von {Waldbäumen} unter sich ändernden {Klimabedingungen} - {Auswertung} der {Beobachtungen} in den {Internationalen} {Phänologischen} {Gärten} und {Möglichkeiten} der {Modellierung} von {Phänodaten}.},
	volume = {164},
	author = {Menzel, Annette},
	year = {1997},
}
